services:
  10dockge:
    container_name: 10dockge
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      - 20010:5001/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /zzz/10dockge/data:/app/data
      - /zzz/10dockge/stacks:/opt/stacks
    networks:
      www:
        ipv4_address: 172.20.1.0
networks:
  www:
    external: true





    